---
- apt: update_cache=yes cache_valid_time=3600
- apt_repository: repo='ppa:git-core' update_cache=yes
- apt: pkg={{item}} state=latest install_recommends=no
  with_items:
  - python-pycurl
  - python-psycopg2
  - git-core
  - tig
  - tmux
  - ufw
  - htop
  - mc
  - zsh
  - vim
  - curl
  - unzip
  - apache2-utils
- name: generate locale
  command: /usr/sbin/locale-gen {{locale}}
- name: set locale to locale
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
- name: conf dir
  file: name=/home/vagrant/conf state=directory
- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh
- name: deploy .zshrc
  template: src=files/zshrc dest=/home/vagrant/conf/zshrc owner=vagrant
- name: remove standard zshrc
  file: path=/home/vagrant/.zshrc state=absent
- name: Create conf folder in home directory
  file: path=/home/vagrant/conf/ state=directory owner=vagrant
- name: symlink zshrc
  file: path=/home/vagrant/.zshrc src=/home/vagrant/conf/zshrc state=link owner=vagrant
- name: Set zsh as default shell
  user: name=vagrant shell=/bin/zsh
