---
- apt_key: url=https://get.docker.io/gpg state=present
- apt_repository: repo='deb https://get.docker.io/ubuntu docker main' update_cache=yes
- apt: pkg={{item}} state=latest install_recommends=no
  with_items:
  - lxc-docker
