---
- apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
- apt_repository: repo='deb https://deb.nodesource.com/node_0.12 trusty main' state=present  update_cache=yes
- apt: pkg={{item}} state=latest install_recommends=no
  with_items:
  - nodejs
- npm: name={{item}} global=true
  with_items:
  - coffee-script
