---
- apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes
- apt: pkg={{item}} state=latest install_recommends=no
  with_items:
  - nodejs
- npm: name={{item}} global=true
  with_items:
  - coffee-script
