---
# Needed for add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed update-cache=yes
  tags:
    - apt

- name: Add repository key
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present
  tags:
    - apt

- name: Add Cassandra 2.1 repository
  apt_repository: repo='{{ cassandra_2_1.repo }}' state=present
  when: cassandra.version_branch == '2.1'
  tags:
    - apt

- name: Add Cassandra 2.2 repository
  apt_repository: repo='{{ cassandra_2_2.repo }}' state=present
  when: cassandra.version_branch == '2.2'
  tags:
    - apt
